server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: kafka-service
          uri: http://localhost:8080
          predicates:
            - Path=/kafka-service/**
          filters:
            - StripPrefix=1

